// components/Footer.vue
<template>
  <div class="footer">
    <!-- <Logo /> -->
    <h4>{{ msg }}</h4>
    <h5>Made with ❤️ by
      <a
        href="https://nebe.bio.link"
        target="_blank"
        rel="noopener noreferrer"
        class="button--grey"
      >
        Óscar 'Nebe' Abad
      </a>
      © 2022</h5>
    <!-- <div class="links">
      <a
        href="https://github.com/nuxt/nuxt.js"
        target="_blank"
        rel="noopener noreferrer"
        class="button--grey"
      >
        GitHub
      </a>
    </div> -->
  </div>
</template>

<script>
export default {
  name: 'Footer',
  props: {
    msg: String
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>


.footer {
  margin: 20px auto;
  padding: 0px auto;
  padding-bottom: 60px;
  /* border-top: 1px solid var(--gray); */
  color: var(--gray);
}
h4 {
  margin: 10px auto;
}
h5 {
  /* font-family: 'Fjalla One', sans-serif; */
  font-weight: 200;
  font-size: 14px;
  color: var(--secondary);
}
a {
  color: var(--primary);
}
</style>

// src/components/Footer/Footer.tsx
const Footer = () => {
  return (
    <footer className="footer flex flex-col text-xs items-center justify-center h-20">
      <h5>Made with <span title="ReactJS + Typescript + NextJS + Tailwind" className="pulsating">❤️</span> by
        <a
          href="https://nebe.bio.link"
          target="_blank"
          rel="noopener noreferrer"
          className="button--grey mx-2"
        >
          Óscar &apos;Nebe&apos; Abad
        </a>
        © 2022</h5>
    </footer>
  )
}
export default Footer
